const listingData = [
    {
        id: 1,
        title: 'Anjuna Beach, India',
        type: 'Home',
        guests: 4,
        price: 120,
        rating: 4.8,
        image: 'https://a0.muscache.com/im/pictures/miso/Hosting-39986130/original/8a6cde11-7be0-44a0-a208-e4740cd5efb7.jpeg?im_w=960&im_format=avif',
        category: 'Beachfront',
    },
    {
        id: 2,
        title: 'Tiny home, Shinano',
        type: 'Private Room',
        guests: 2,
        price: 90,
        rating: 2.7,
        image: 'https://a0.muscache.com/im/pictures/b2c0f556-f726-4db8-985f-25a668369fe7.jpg?im_w=720&im_format=avif',
        category: 'Cabins',
    },
    {
        id: 3,
        title: 'Dhonakulhi, Maldives',
        type: 'Home',
        guests: 5,
        price: 250,
        rating: 5.0,
        image: 'https://a0.muscache.com/im/pictures/miso/Hosting-912305060013575560/original/eb4120bb-e281-41eb-bef5-7dac96eb90f2.jpeg?im_w=720&im_format=avif',
        category: 'Luxury',
    },
    {
        id: 4,
        title: 'Entire villa in Mashobra, India',
        type: 'Home',
        guests: 6,
        price: 150,
        rating: 4.6,
        image: 'https://a0.muscache.com/im/pictures/miso/Hosting-1208478853883571250/original/03aef6b8-3992-463d-94ca-2422c2d82757.jpeg?im_w=960&im_format=avif',
        category: 'Unique Stays',
    },
    {
        id: 5,
        title: 'Room in Leh, India',
        type: 'Private Room',
        guests: 3,
        price: 75,
        rating: 4.2,
        image: 'https://a0.muscache.com/im/pictures/b4729e33-7007-4d22-97d3-2eff3bd46643.jpg?im_w=720&im_format=avif',
        category: 'Budget',
    },
    {
        id: 6,
        title: 'Room in Pandtehr, India',
        type: 'Home',
        guests: 8,
        price: 180,
        rating: 4.9,
        image: 'https://a0.muscache.com/im/pictures/202659e3-a80e-45a5-a728-5ea1d3d4500d.jpg?im_w=960&im_format=avif',
        category: 'Family-Friendly',
    },
    {
        id: 7,
        title: 'Room in Canning, Argentina',
        type: 'Apartment',
        guests: 4,
        price: 110,
        rating: 4.5,
        image: 'https://a0.muscache.com/im/pictures/hosting/Hosting-1306617299561788874/original/873c1efe-81cc-4472-8d22-a4aae3b640b4.jpeg?im_w=960&im_format=avif',
        category: 'Pet-Friendly',
    },
    {
        id: 8,
        title: 'Entire villa in Tambon Ratsada, Thailand',
        type: 'Villa',
        guests: 10,
        price: 500,
        rating: 5.0,
        image: 'https://a0.muscache.com/im/pictures/miso/Hosting-37922090/original/3e98dbd8-1b21-49b2-afc7-f1a227470804.jpeg?im_w=720&im_format=avif',
        category: 'Luxury',
    },
    {
        id: 9,
        title: 'Trendy Tiny House',
        type: 'Tiny Home',
        guests: 2,
        price: 70,
        rating: 4.4,
        image: 'https://images.pexels.com/photos/1640776/pexels-photo-1640776.jpeg',
        category: 'Unique Stays',
    },
    {
        id: 10,
        title: 'Chic Studio Near the Beach',
        type: 'Studio',
        guests: 2,
        price: 95,
        rating: 4.6,
        image: 'https://images.pexels.com/photos/2924726/pexels-photo-2924726.jpeg',
        category: 'Beachfront',
    },
    {
        id: 11,
        title: 'Rustic Farmhouse Getaway',
        type: 'Home',
        guests: 5,
        price: 160,
        rating: 4.7,
        image: 'https://images.pexels.com/photos/2076906/pexels-photo-2076906.jpeg',
        category: 'Family-Friendly',
    },
    {
        id: 12,
        title: 'Cozy Treehouse Retreat',
        type: 'Treehouse',
        guests: 4,
        price: 120,
        rating: 4.8,
        image: 'https://images.pexels.com/photos/1863735/pexels-photo-1863735.jpeg',
        category: 'Cabins',
    },
    {
        id: 13,
        title: 'Lavish Penthouse Suite',
        type: 'Penthouse',
        guests: 3,
        price: 400,
        rating: 4.9,
        image: 'https://images.pexels.com/photos/1675590/pexels-photo-1675590.jpeg',
        category: 'Luxury',
    },
    {
        id: 14,
        title: 'Stylish City Apartment',
        type: 'Apartment',
        guests: 4,
        price: 130,
        rating: 4.6,
        image: 'https://images.pexels.com/photos/1662562/pexels-photo-1662562.jpeg',
        category: 'Unique Stays',
    },
    {
        id: 15,
        title: 'Modern Beachfront Condo',
        type: 'Condo',
        guests: 6,
        price: 250,
        rating: 4.8,
        image: 'https://images.pexels.com/photos/2384691/pexels-photo-2384691.jpeg',
        category: 'Beachfront',
    },
    {
        id: 16,
        title: 'Charming Cabin in the Woods',
        type: 'Cabin',
        guests: 5,
        price: 140,
        rating: 4.7,
        image: 'https://images.pexels.com/photos/2899906/pexels-photo-2899906.jpeg',
        category: 'Cabins',
    },
    {
        id: 17,
        title: 'Spacious Family Lodge',
        type: 'Lodge',
        guests: 12,
        price: 300,
        rating: 4.5,
        image: 'https://images.pexels.com/photos/1593631/pexels-photo-1593631.jpeg',
        category: 'Family-Friendly',
    },
    {
        id: 18,
        title: 'Unique Hobbit House',
        type: 'House',
        guests: 2,
        price: 110,
        rating: 4.9,
        image: 'https://images.pexels.com/photos/2889660/pexels-photo-2889660.jpeg',
        category: 'Unique Stays',
    },
    {
        id: 19,
        title: 'Budget-Friendly Beach Apartment',
        type: 'Apartment',
        guests: 4,
        price: 85,
        rating: 4.3,
        image: 'https://images.pexels.com/photos/2566852/pexels-photo-2566852.jpeg',
        category: 'Budget',
    },
    {
        id: 20,
        title: 'Luxury Retreat with Pool',
        type: 'Villa',
        guests: 8,
        price: 450,
        rating: 5.0,
        image: 'https://images.pexels.com/photos/3027040/pexels-photo-3027040.jpeg',
        category: 'Luxury',
    },
    {
        id: 21,
        title: 'Pet-Friendly Mountain Lodge',
        type: 'Lodge',
        guests: 6,
        price: 170,
        rating: 4.6,
        image: 'https://images.pexels.com/photos/1455771/pexels-photo-1455771.jpeg',
        category: 'Pet-Friendly',
    },
    {
        id: 22,
        title: 'Trendy Urban Loft',
        type: 'Loft',
        guests: 3,
        price: 150,
        rating: 4.5,
        image: 'https://images.pexels.com/photos/2767402/pexels-photo-2767402.jpeg',
        category: 'Unique Stays',
    },
    {
        id: 23,
        title: 'Affordable Studio with Beach Access',
        type: 'Studio',
        guests: 2,
        price: 95,
        rating: 4.4,
        image: 'https://images.pexels.com/photos/1166482/pexels-photo-1166482.jpeg',
        category: 'Beachfront',
    },
    {
        id: 24,
        title: 'Luxury Eco-Friendly Cabin',
        type: 'Cabin',
        guests: 4,
        price: 210,
        rating: 4.8,
        image: 'https://images.pexels.com/photos/3882152/pexels-photo-3882152.jpeg',
        category: 'Cabins',
    },
    {
        id: 25,
        title: 'Family-Friendly Beach House',
        type: 'House',
        guests: 10,
        price: 350,
        rating: 4.7,
        image: 'https://images.pexels.com/photos/3141372/pexels-photo-3141372.jpeg',
        category: 'Family-Friendly',
    },
    {
        id: 26,
        title: 'Modern Apartment with Balcony',
        type: 'Apartment',
        guests: 2,
        price: 120,
        rating: 4.5,
        image: 'https://images.pexels.com/photos/2887806/pexels-photo-2887806.jpeg',
        category: 'Unique Stays',
    },
    {
        id: 27,
        title: 'Charming Cottage with Garden',
        type: 'Cottage',
        guests: 4,
        price: 140,
        rating: 4.6,
        image: 'https://images.pexels.com/photos/2108035/pexels-photo-2108035.jpeg',
        category: 'Family-Friendly',
    },
    {
        id: 28,
        title: 'Rustic River Cabin',
        type: 'Cabin',
        guests: 6,
        price: 160,
        rating: 4.5,
        image: 'https://images.pexels.com/photos/1894278/pexels-photo-1894278.jpeg',
        category: 'Cabins',
    },
    {
        id: 29,
        title: 'Tranquil Beach House',
        type: 'House',
        guests: 8,
        price: 300,
        rating: 5.0,
        image: 'https://images.pexels.com/photos/1158319/pexels-photo-1158319.jpeg',
        category: 'Beachfront',
    },
    {
        id: 30,
        title: 'Stylish Loft in Downtown',
        type: 'Loft',
        guests: 2,
        price: 130,
        rating: 4.6,
        image: 'https://images.pexels.com/photos/1664405/pexels-photo-1664405.jpeg',
        category: 'Unique Stays',
    },
];

module.exports = listingData;